version: '3'

services:
  backend:
    build: backend/
    ports:
      - 5000:5000
    networks:
      - deploy_network
    container_name: backend

  frontend:
    build: frontend/
    depends_on:
      - backend
    ports:
      - 3000:3000
    networks:
      - deploy_network
    container_name: frontend

networks:
  deploy_network:
    driver: bridge